### ISSUE TITLE
Add crcomlib at the end of index.html, after the other script

### ISSUE THREAD

**Issue by Mirage-AV** [fat-so/ch5-test#1]
<script src="https://cdn.jsdelivr.net/npm/@crestron/ch5-crcomlib@latest/build_bundles/umd/cr-com-lib.js"></script>

**Comment by fat-so** [comment]
in that case I don't need Import  crcomlib at html 
because I import it at js 
but yes is maybe could fix some bug or wrong thing

**Comment by fat-so** [comment]
but thx your reply
